version: '3.8'
services:
  backend-service:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - sales-net

  frontend-service:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend-service:8000
    depends_on:
      - backend-service
    networks:
      - sales-net

networks:
  sales-net:
    driver: bridge